language: cpp

env:
  global:
    - CMAKE_TOOLCHAIN_FILE=${HOME}/vcpkg/scripts/buildsystems/vcpkg.cmake

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-multilib
      - g++-multilib

dist: bionic

matrix:
  include:
    - os: linux
      env: CONFIG=Debug VCPKG_DEFAULT_TRIPLET=x64-linux VCPKG_TARGET_TRIPLET=x64-linux CMAKE_C_FLAGS=-m64 CMAKE_CXX_FLAGS=-m64
    - os: linux
      env: CONFIG=Release VCPKG_DEFAULT_TRIPLET=x64-linux VCPKG_TARGET_TRIPLET=x64-linux CMAKE_C_FLAGS=-m64 CMAKE_CXX_FLAGS=-m64
    - os: linux
      env: CONFIG=Debug VCPKG_DEFAULT_TRIPLET=x86-linux VCPKG_TARGET_TRIPLET=x86-linux CMAKE_C_FLAGS=-m32 CMAKE_CXX_FLAGS=-m32
    - os: linux
      env: CONFIG=Release VCPKG_DEFAULT_TRIPLET=x86-linux VCPKG_TARGET_TRIPLET=x86-linux CMAKE_C_FLAGS=-m32 CMAKE_CXX_FLAGS=-m32

before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - export CMAKE_INSTALL_SCRIPT=cmake-3.15.0-Linux-x86_64.sh
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.0/${CMAKE_INSTALL_SCRIPT}
  - chmod +x ${CMAKE_INSTALL_SCRIPT}
  - ./${CMAKE_INSTALL_SCRIPT} --prefix=$HOME/usr --exclude-subdir --skip-license

install:
  - mkdir -p ${HOME}/vcpkg

  - set -e
  - pushd ${HOME}/vcpkg
  - git init
  - git config remote.origin.url >&- || git remote add origin https://github.com/Microsoft/vcpkg.git
  - git fetch origin master
  - git checkout master 2>/dev/null || git checkout -b master origin/master
  - ./bootstrap-vcpkg.sh
  - |
    touch ./triplets/community/x86-linux.cmake
    echo -e "set(VCPKG_TARGET_ARCHITECTURE x86)\nset(VCPKG_CRT_LINKAGE dynamic)\nset(VCPKG_LIBRARY_LINKAGE static)\nset(VCPKG_CXX_FLAGS -m32)\nset(VCPKG_C_FLAGS -m32)\nset(VCPKG_CMAKE_SYSTEM_NAME Linux)" > ./triplets/community/x86-linux.cmake
  - ./vcpkg install mongo-c-driver
  - ./vcpkg integrate install
  - popd

script:
  - set -e
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE} -DVCPKG_TARGET_TRIPLET=${VCPKG_TARGET_TRIPLET} -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS} -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} ..
  - make -j
  - cd ..

cache:
  directories:
    - ${HOME}/vcpkg/

deploy:
  provider: releases
  api_key:
    secure: "dMQVeKa9bWRlUx5cFGpyPpC0G2seadTNWGbL7Vr/b3yyLPfT29zOmseQ5+azNpomtkeOBhf+7DlewZEo7U8Mr+xFfJxP47L8mWePe6UJLz7fgX4phhAU2ZA4TifkUsUE7nQB8q3eBS0kqY12cP3rxSDl9tCYyQT555neUC5MjkDNPACD72RXngdhEE2zsE3IzT8FywfoxjFv+FfeqbnLgULwg+GuM4p5vGERGMsan8aPQMCNXOAfT5wDWMeuIPefo8B5EqgZQh0UNtDLbVMReuXPpEBYvw1pmofKImbs1k/TsPjSLAwu2ykm4V8Vl7HJfCmox7kzUVdPhVBZeZDcz2dZh16KevU+loWFCvhYtGwa/guT/qe9IyPzpUm2AXrZinDv98JUY11Kwezm3GWIACEAEUcnsI9Pm6f5oHGB+nrSE5W5C9H1HIxNeVJMnjmXHNlRuEgYl1rB0K1cAsBdTXW6eW9QUp1r/Q5HrZJXJsWQWeiz5astU9fmf2Fn07lJQy+Omj1snYx8vYCK1sZK2QKfpX5Tjuqa8RkXO6ACANSFbRnizE/GsbxS9YOYZ0HdP8N5ia+uoTeE8B3f+jPBv9gZeDJUar+55ubdtHUKyj6rdsBT8CajxNK2wqIOiqh7px9a0IpJcvYvoazC0p0/IuKWkXU4uXyVuSV/Fq4Z1q0="
  file_glob: true
  file: build/**/*.dll
  skip_cleanup: true
  draft: true
  on:
    tags: true
    condition: $CONFIG = Release
