platform:
  - x86
  - x64

image:
  - Visual Studio 2019

environment:
 
  VCPKG_DEFAULT_TRIPLET: x64-windows-static
  VCPKG_TARGET_TRIPLET: x64-windows-static
  CMAKE_TOOLCHAIN_FILE: C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake
  MSVC_VERSION: 64
  CL_VERSION: x64
  matrix:
    
  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: Linux build
    appveyor_build_worker_image: Visual Studio 2019

configuration:
  - Debug
  - Release

for:
  -
    matrix:
      only:
         - job_name: Windows 32 Bit
    environment:
       - VCPKG_DEFAULT_TRIPLET: x86-windows-static
         VCPKG_TARGET_TRIPLET: x86-windows-static
         MSVC_VERSION: 32
         CL_VERSION: Win32
  -     
    matrix:
  
      only:
          - platform: x64
            job_name: Windows 64 Bit
      environment:
        VCPKG_DEFAULT_TRIPLET: x64-windows-static
        VCPKG_TARGET_TRIPLET: x64-windows-static
        MSVC_VERSION: 64
        CL_VERSION: Win64
  -
    matrix:
      only:
          - platform: x86
          - job_name: Linux 32 Bit
      environment:
        VCPKG_DEFAULT_TRIPLET: x86-linux-static
        VCPKG_TARGET_TRIPLET: x86-linux-static
        MSVC_VERSION: 32
        CL_VERSION: Lin32
  -    
    matrix:
      only:
          - platform: x64
          - job_name: Linux 64 Bit
      environment:
        VCPKG_DEFAULT_TRIPLET: x64-linux-static
        VCPKG_TARGET_TRIPLET: x64-linux-static
        MSVC_VERSION: 64
        CL_VERSION: Lin64


init:
  - appveyor version
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars%MSVC_VERSION%.bat"

install:
  - vcpkg remove --outdated --recurse
  - vcpkg install mongo-c-driver
  - vcpkg integrate install

  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - mkdir build
  - cd build

  - cmake -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_TOOLCHAIN_FILE=%CMAKE_TOOLCHAIN_FILE% -DVCPKG_TARGET_TRIPLET=%VCPKG_TARGET_TRIPLET% -A %CL_VERSION% ..
  - cmake --build . --target ALL_BUILD --config %configuration%
  - cd %APPVEYOR_BUILD_FOLDER%

cache:
  - C:\Tools\vcpkg\installed\ -> .appveyor.yml

artifacts:
  - path: 'build\**\*.dll'
    name: module

deploy:
  provider: GitHub
  auth_token:
    secure: "knRWM52k9RrInpuCE5mwYo3+YdPptnKTg7J82JUyMFFD5mw9ZC2LadWsaS4TPJAE"
  artifact: module
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
    CONFIGURATION: Release

